### ISSUE TITLE
Remove codes.json and Restructure languages.json

### ISSUE THREAD

**Issue by Androbin** [apertium/pairviewer#4]
> Implement an algorithm to generate 2-to-3-letter mappings for available languages based on having the identical language name in `languages.json` instead of loading the huge list from `codes.json`.

@JPJPJPOPOP /cc
@jonorthwash /cc

**Comment by Androbin** [comment]
Wasn't this part of the GCI task?
https://codein.withgoogle.com/tasks/5095809236336640/

**Comment by sushain97** [comment]
This doesn't really make sense. Paring down languages.json does.

**Comment by Androbin** [comment]
@sushain97 Why was this part of the task description in the first place?

**Comment by sushain97** [comment]
I don't know.

**Comment by JPJPJPOPOP** [comment]
@Androbin I talked with firespeaker about this. He said it was okay to keep the `codes.json` because it is still very small compared to the `languages.json` (3kb vs 190kb).

**Comment by jonorthwash** [comment]
I think it was part of that task, and I think it's already been solved??

**Comment by Androbin** [comment]
It was part of the task.
The task has been accepted.
Fixing this was dropped as a requirement.

**Comment by jonorthwash** [comment]
But it's already been solved, right?

**Comment by JPJPJPOPOP** [comment]
@jonorthwash It has been _'solved'_ by deeming it not needed. I talked to you about this :P. Basically as I said before, the `codes.json` is very small compared to the `languages.json` (3kb vs 190kb).

**Comment by jonorthwash** [comment]
hmm yeah okay...

**Comment by jonorthwash** [comment]
So let's close this issue?

**Comment by JPJPJPOPOP** [comment]
Sure, go ahead.
